import torch
from transformers import pipeline

def is_generated_by_ai(paragraph,model):
    # Load the text classification pipeline
    text_classifier = pipeline("text-classification", model=model)

    # Classify the input paragraph
    result = text_classifier(paragraph)

    # You can adjust this threshold based on experimentation
    confidence_threshold = 0.5

    # Check if the label is consistent with AI-generated text
    label = result[0]['label']
    confidence = result[0]['score']
    if label == 'LABEL_1' and confidence >= confidence_threshold:
        return ["AI",confidence]
    else:
        return ["Human",confidence]

if __name__ == "__main__" :
    input_text = "This is an example paragraph."
    model = "nlptown/bert-base-multilingual-uncased-sentiment"
    generated_by_ai = is_generated_by_ai(input_text,model)
    print("The text seems to be generated by " + generated_by_ai[0] + " with a confidence of "+ str(generated_by_ai[1]))

    